# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChemistryAR' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ChemistryAR
  pod 'IQKeyboardManager'
  pod 'SwiftMessages'
  pod 'SVProgressHUD'
  pod 'SDWebImage'
  pod 'SpreadsheetView'
  pod 'ESTabBarController-swift'
  pod 'Firebase/Core'
  pod 'Firebase/Storage'
  pod 'Alamofire'
  pod 'ObjectMapper'
  pod 'TLPhotoPicker'
  pod 'Panels'
  pod 'ReachabilitySwift'
end
